### ISSUE TITLE
Access policy cause the Prisma runtime validation error

### ISSUE THREAD

**Issue by jiashengguo** [zenstackhq/zenstack#704] opened 2023-09-20 12:58 UTC
Use the below zmodel schema file:
https://github.com/noufalr/open/blob/main/schema.zmodel

running the below code:
```ts
    const client = enhance(prisma, { user: { id: 1 } };
    const myCorseIds = [randomUUID()];
    const result = await client.enrollment.count({
        where: {
            course_id: {
                in: myCorseIds,
            },
        },
    });
```

It shows the error in my machine:
```bash
Argument `id`: Invalid value provided. Expected StringFilter or String, provided Int.
    at /Users/jiasheng/branch/my-try-prisma/src/zen.ts:10:44,
    at step (/Users/jiasheng/branch/my-try-prisma/src/zen.ts:33:23),
    at Object.next (/Users/jiasheng/branch/my-try-prisma/src/zen.ts:14:53),
    at /Users/jiasheng/branch/my-try-prisma/src/zen.ts:8:71,
    at new Promise (<anonymous>),
    at __awaiter (/Users/jiasheng/branch/my-try-prisma/src/zen.ts:4:12),
    at bookSeat (/Users/jiasheng/branch/my-try-prisma/src/zen.ts:44:12),
    at /Users/jiasheng/branch/my-try-prisma/src/zen.ts:22:11,
    at step (/Users/jiasheng/branch/my-try-prisma/src/zen.ts:33:23) {
  name: 'PrismaClientValidationError',
  clientVersion: '5.2.0',
```
  

But according to the customer, the error is:
```bash
Unknown argument `is`. Available options are listed in green.
    at load (D:/Dev/Repos/lmsapp/src/routes/(app)/courses/+page.server.ts:40:57),
    at async Module.load_server_data (D:/Dev/Repos/lmsapp/node_modules/@sveltejs/kit/src/runtime/server/page/load_data.js:57:17),
    at async eval (D:/Dev/Repos/lmsapp/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:150:13) {
  name: 'PrismaClientValidationError',
  clientVersion: '5.3.1',
```

**Comment by ymc9** [comment] 2023-09-20 20:44
Two problems here:
1. The context `user` passed to `enhance` has mismatching `id` field typing. This should be validated against `User` model.
2. After fixing the `id` typing, you can see the real error. The problem is with rules like `authors == auth()`, which should actually be `authors?[this == auth()`. CLI hasn't caught such typing error.

**Comment by ymc9** [comment] 2023-10-03 01:06
The CLI now captures the errors in comparing things like `authors == auth()`. I'm keeping this issue open for tracking how to validate typing of the user context.

**Comment by ymc9** [comment] 2024-03-24 17:51
The user context now has strong typing. Closing.

**Closed by ymc9** 2024-03-24 17:51 UTC
Labels: in-progress
