### ISSUE TITLE
Policy definition cannot be loaded from default location

### ISSUE THREAD

**Issue by quinnvaughn** [zenstackhq/zenstack#421] opened 2023-05-19 00:14 UTC
**Description and expected behavior**
I am attempting to add the enhanced prisma client in the context of a graphql server, and I'm getting this error while attempting to codegen from graphql-codegen: "Context creation failed: Policy definition cannot be loaded from default location". I couldn't find anything on this error. It works fine when I just use the backend separate, and the codegen also works fine when using the normal prisma client.
```

function createZenstack(authUser: AuthUser | undefined) {
	return withPolicy(prisma, { user: authUser })
}

export async function createContext(req: IncomingMessage): Promise<Context> {
	const auth = req.headers.authorization?.split("Bearer ")[1] || ""
	const decoded = verifyToken(auth)
	let currentUser: User | null = null
	if (decoded?.id && typeof decoded.id === "string") {
		currentUser = await prisma.user.findUnique({
			where: {
				id: decoded.id,
			},
		})
	}
	return {
		prisma: createZenstack({ id: currentUser?.id }),
		currentUser,
	}
}
```

There is nothing in the examples about how to use this in GraphQL land, the only backend example is with express, so I'm not sure why this fails specifically with the codegen. The easiest temporary fix for now is to just not use the enhanced version but that defeats some of the point.

**Environment (please complete the following information):**

-   ZenStack version: 1.0.0-alpha.116
-   Prisma version: 4.14.1
-   Database type: Postgres

**Comment by ymc9** [comment] 2023-05-19 00:21
Hi @quinnvaughn , GQL hasn't been a focus yet but I'm interested in getting the main scenarios to work. By graphql-codegen you mean [this one](https://the-guild.dev/graphql/codegen) right?

The error is usually caused by a mismatch between ZenStack's code generation location and its runtime location. I'll need to build a repro to investigation. Is your project by any chance publicly accessible now? If not, I'll see if I can get something with a standard GQL setup.

**Comment by quinnvaughn** [comment] 2023-05-19 00:23
1. Yes
2. Not public code, but I'm using Apollo Server's standalone server and passing in that function ^^ into the context like `({req}) => createContext(req)` which I assume would be enough to replicate it along with some generic types. I'm using Apollo Client/React on the frontend, no weird setup.

**Comment by quinnvaughn** [comment] 2023-05-19 00:23
Also possibly relevant, my zenstack code is in a zenstack folder under src ie `src/zenstack/allFiles.zmodel`

**Comment by ymc9** [comment] 2023-05-19 00:24
Got it. Let me try it out, and will keep you updated on my findings. Thanks for reporting this!

**Comment by jiashengguo** [comment] 2023-05-21 14:03
Hi, @quinnvaughn   I tried to reproduce your problem with a simple ApolloServer and graphql-codegen as you used:
https://github.com/jiashengguo/graphql-server-example

It worked fine on my machine. Can you try it in your environment?

BTW,  as @ymc9 mentioned, this problem is usually caused by generated `.zenstack` folder that can’t be referenced by `@zenstackhq/runtime` package.   Can you try to identify where the `.zenstack` folder is generated in your project by running:

```bash
find . -type d -name ".zenstack"
```

For your concern, the location of `zmodel`file should not be an issue.  ZenStack CLI supports specifying the schema file using `--schema` argument like:
```bash
npx zenstack generate --schema src/zenstack/schema.zmodel
```
I don’t quite sure how you did that by 
> use a custom path for the npm script.   

If it's not the way above, can you try it instead to see whether it could solve your problem?

**Comment by quinnvaughn** [comment] 2023-05-31 17:48
It seems to work when I change the code slightly to this:

```
import { prisma } from "./db"
import { verifyToken } from "./lib/jwt"
import { PrismaClient, User } from "@prisma/client"
import { withPolicy } from "@zenstackhq/runtime"
import { IncomingMessage } from "http"

export type Context = {
	prisma: PrismaClient
	currentUser: User | null
}

function createZenstack(authUser: User | undefined) {
	return withPolicy(prisma, { user: authUser })
}

export async function createContext(req: IncomingMessage): Promise<Context> {
	const auth = req.headers.authorization?.split("Bearer ")[1] || ""
	const decoded = verifyToken(auth)
	let currentUser: User | null = null
	if (decoded?.id && typeof decoded.id === "string") {
		currentUser = await prisma.user.findUnique({
			where: {
				id: decoded.id,
			},
		})
	}
	return {
		prisma: createZenstack(currentUser || undefined),
		currentUser,
	}
}
```

And completely ignore your AuthUser type. Although I'm not sure why you have it as `AuthUser | undefined` when a findUnique will return null, forces me to do the `|| undefined` to play nice.

**Comment by quinnvaughn** [comment] 2023-05-31 17:54
So actually this just made TS work, the prisma instance itself seems to not be working.

Also to answer your original question it was `./node_modules/@zenstackhq/runtime/node_modules/.zenstack`

**Comment by jiashengguo** [comment] 2023-05-31 18:13
It is supposed to be  `./node_modules/.zenstack` to make it work.   Did you use the command I mentioned above running in the root folder of your repo:
`npx zenstack generate --schema src/zenstack/schema.zmodel`

**Comment by jiashengguo** [comment] 2023-06-06 20:54
@quinnvaughn  In the latest release 1.0.0-alpha.126, we made a change that might be relevant to this issue. Maybe you can update it, then try it again?

**Comment by quinnvaughn** [comment] 2023-06-13 23:59
Sure I'll check it out. Sorry, been busy.

**Comment by ymc9** [comment] 2023-06-30 07:31
Closing for now until people hit it again.

**Closed by ymc9** 2023-06-30 07:31 UTC

**Comment by quinnvaughn** [comment] 2023-08-08 22:32
Yeah this still doesn't work. It tells me "Context creation failed: Policy definition cannot be loaded from default location"
