### ISSUE TITLE
[BUG] @@auth doesn't work if a User model is defined

### ISSUE THREAD

**Issue by onimitch** [zenstackhq/zenstack#1694] opened 2024-09-11 11:19 UTC
**Description and expected behavior**
If you specify `@@auth` on a model but also have a `User` model defined, Zenstack uses the `User` model for the `AuthUser` type.

```
model AuthUser {
    @@auth
    id String @id
}

model User {
    id String @id @default(cuid())
}
```

With the models above, enhance expects a type matching `User` despite me marking `AuthUser` as `@@auth`.

Currently my workaround is to not use `@@auth`, and name my AuthUser model `User`, but that's forced me to name my "real" User model to something else, which I don't want to do.

```
model User {
    id String @id
}

model RealUser {
    id String @id @default(cuid())
}
```

**Expected behaviour**

I can use `@@auth` on a Model and still define a User model myself.

**Environment (please complete the following information)**

-   ZenStack version: 2.5.1
-   Prisma version: 5.18.0
-   Database type: Postgresql

**Comment by onimitch** [comment] 2024-09-11 11:33
I've also just noticed that with this set up:

`model User {
    @@ignore
    id String @id
}

model RealUser {
    id String @id @default(cuid())
}
`

The type of User is simply `Record<string, unknown>`. It would be nice if Zenstack could still generate the correctly type based on the Model fields.

**Comment by onimitch** [comment] 2024-09-11 11:36
OK going to edit the bug. It looks like @@ignore is a red herring. @@auth simply doesn't work if you have a model called User.

**Comment by ymc9** [comment] 2024-11-14 22:22
> model AuthUser {
>     @@auth
>     id String @id
> }
> 
> model User {
>     id String @id @default(cuid())
> }

Hi @onimitch , thanks for filing this. I tried with the latest release but couldn't reproduce the issue with this model:

```prisma
model AuthUser {
    @@auth
    id String @id
}

model User {
    id String @id @default(cuid())
}
```

Do you have a project that can expose this? Thanks!

**Comment by ymc9** [comment] 2024-11-14 22:23
Btw, v2.9 will allow to use a "type" as "@@auth" so you don't need to use the "@@ignore" hack anymore.

**Comment by ymc9** [comment] 2024-11-22 20:30
Closing for now. Please feel free to reactive if it's still an issue.

**Closed by ymc9** 2024-11-22 20:30 UTC
Labels: need-repro
