### ISSUE TITLE
Cannot use enum as field default when enum is declared after model

### ISSUE THREAD

**Issue by he-la** [zenstackhq/zenstack#389] opened 2023-05-04 21:32 UTC
**Description and expected behavior**
#204 attempts to implement setting enum variants as field defaults (prisma supports this). But this does not work when the enum is declared after the model:

```
${prelude}

model M {
    e E @default(E1)
}

enum E {
    E1
    E2
}
```

will fail with `Value is not assignable to parameter []`

**Environment (please complete the following information):**

-   ZenStack version: 1.0.0-alpha.113
-   Prisma version: 4.11.0
-   Database type: Postgresql

**Comment by ymc9** [comment] 2023-05-04 21:56
You're right, declaration order shouldn't matter. Looks like a bug

**Comment by ymc9** [comment] 2023-05-05 19:24
Hi @he-la , I tried to reproduce the issue but couldn't succeed. Here's my zmodel:

```prisma
generator client {
    provider = "prisma-client-js"
}

datasource db {
    provider = "postgresql"
     url      = env("DATABASE_URL")
}

model M {
    id Int @id
    e E @default(E1)
}

enum E {
    E1
    E2
}
```

Maybe it's somewhat different from what you tried with?

**Comment by ymc9** [comment] 2023-05-29 01:32
Closing as not reproducible.

**Closed by ymc9** 2023-05-29 01:32 UTC
Labels: prisma-parity, need-repro
