### ISSUE TITLE
Zenstack Access PolicyError compiling generated code -  Module '"@prisma/client"' has no exported member...

### ISSUE THREAD

**Issue by dannyduncan** [zenstackhq/zenstack#661] opened 2023-09-01 01:43 UTC
**Description and expected behavior**
I'm using Zenstack to modularize a set of models and enum fields. When I run zenstack generate, both the Plugin Prisma and Metadata successfully run but the Access Policy plugin generates the following error:

Module '"@prisma/client"' has no exported member '<<ENUM FIELD>>'

I get this error for each defined enum field.

**Environment (please complete the following information):**

-   ZenStack version: 1.0.0-beta.20
-   Prisma version: 5.2.0
-   Database type: Postgresql

**Additional context**
I'm importing my enum fields similar to my models within the schema.zmodel file. Please see example below:

import "enums/names"

My thinking is that maybe enum imports are not fully supported for the Access Policy plugin. If this is the case, I would hope that I could disable the Access Policy plugin - I'm currently not using any access policies.

**Comment by ymc9** [comment] 2023-09-01 02:10
Hi @dannyduncan , thanks for reporting this issue. Just to make sure I understand the usage here: the imported "enums/names.zmodel" contains only enum declarations, right?

**Comment by dannyduncan** [comment] 2023-09-01 13:56
That's correct. The enums/names.zmodel only contains the following:

enum Names {
    ALPHA
    BRAVO
    CHARLIE
}

**Comment by ymc9** [comment] 2023-09-01 14:30
Got it. We'll look into it and update back here. Thank you @dannyduncan !

**Comment by ymc9** [comment] 2023-09-07 06:41
Hi @dannyduncan , I suspect this is related to #674 . Is the enum not used by any model?

**Comment by dannyduncan** [comment] 2023-09-07 12:49
Thanks for checking in. We do in-fact use the enum values in our models.

**Comment by ymc9** [comment] 2023-09-07 14:23
Hi @dannyduncan , after a few tries I still couldn't reproduce the problem. Do you think it's possible to share a simplified version of your zmodel that can trigger the error? Thanks!

**Comment by dannyduncan** [comment] 2023-10-02 19:31
Hey @ymc9 I believe I have a better understanding of the problem. First, please note that I've updated my environment to the following:

ZenStack version: 1.0.1
Prisma version: 5.3.1
Database type: Postgresql

Within my schema.zmodel file I include the prisma plugin to prevent running prisma generate. See below:

```
plugin prisma {
    provider = '@core/prisma'
    output = './prisma/schema.prisma'
    generateClient = false
    format = true
}
```

In that scenario I get the error described above. If I change the snippet above to generateClient = true, the code runs as expected.

What I believe to be happening is that the Access Policy plugin doesn't work as expected when the prisma client is not generated.

Can you test and confirm?

**Comment by ymc9** [comment] 2023-10-02 20:10
Thanks for folllowing up @dannyduncan . I'll try again and see what I can get.

Btw, the latest ZenStack CLI supports a "--no-default-plugins" for the "generate" command, and you can use it to turn off all default plugins. Hope this helps.

**Comment by dannyduncan** [comment] 2023-10-02 23:51
> Thanks for following up @dannyduncan . I'll try again and see what I can get.
> 
> Btw, the latest ZenStack CLI supports a "--no-default-plugins" for the "generate" command, and you can use it to turn off all default plugins. Hope this helps.

Very helpful thanks!

**Comment by dannyduncan** [comment] 2023-10-16 22:19
Hey @ymc9 were you able to confirm the bug?

**Comment by ymc9** [comment] 2023-10-16 22:25
> Hey @ymc9 were you able to confirm the bug?

Hi @dannyduncan , my apologies for not updating here. When "generateClient" is false, "zenstack generate" doesn't automatically run "prisma generate". You'll need to manually run it to get the Prisma TS types generated.

Do you recall why you set that switch ti false?

**Comment by dannyduncan** [comment] 2023-10-30 18:36
> > Hey @ymc9 were you able to confirm the bug?
> 
> Hi @dannyduncan , my apologies for not updating here. When "generateClient" is false, "zenstack generate" doesn't automatically run "prisma generate". You'll need to manually run it to get the Prisma TS types generated.
> 
> Do you recall why you set that switch ti false?

Hi @ymc9 I'm doing db development separate from backend scripting so prefer to create a separation of concerns. Obviously the current solution is to use the "--no-default-plugins" option. If that is the accepted solution, it would be helpful to update the docs to mention any issues when generateClient is set to false. Another solution is have zenstack generate be aware of the prisma plugin configuration and, by default, not run the access policy when generateClient is set to false.

**Comment by ymc9** [comment] 2023-12-24 13:59
Closing since the confusing documentation has been updated.

**Closed by ymc9** 2023-12-24 13:59 UTC
